/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AboutWaiFChat: (typeof import('./src/components/AboutWaiFChat/index.vue'))['default']
    ApplyMessage: typeof import('./src/components/ApplyMessage/index.vue')['default']
    BottomInput: typeof import('./src/components/BottomInput/index.vue')['default']
    ChatPop: (typeof import('./src/components/ChatPop/index.vue'))['default']
    ChatPopup: typeof import('./src/components/ChatPopup/index.vue')['default']
    ContactHome: typeof import('./src/components/ContactHome/index.vue')['default']
    copy: (typeof import('./src/components/MessageDetail/index copy.vue'))['default']
    DefaultContent: typeof import('./src/components/DefaultContent/index.vue')['default']
    ElBadge: (typeof import('element-plus/es'))['ElBadge']
    ElButton: (typeof import('element-plus/es'))['ElButton']
    ElCol: (typeof import('element-plus/es'))['ElCol']
    ElCollapse: (typeof import('element-plus/es'))['ElCollapse']
    ElCollapseItem: (typeof import('element-plus/es'))['ElCollapseItem']
    ElDatePicker: (typeof import('element-plus/es'))['ElDatePicker']
    ElDialog: (typeof import('element-plus/es'))['ElDialog']
    ElDivider: (typeof import('element-plus/es'))['ElDivider']
    ElDrawer: (typeof import('element-plus/es'))['ElDrawer']
    ElDropdown: (typeof import('element-plus/es'))['ElDropdown']
    ElDropdownItem: (typeof import('element-plus/es'))['ElDropdownItem']
    ElDropdownMenu: (typeof import('element-plus/es'))['ElDropdownMenu']
    ElEmpty: (typeof import('element-plus/es'))['ElEmpty']
    ElForm: (typeof import('element-plus/es'))['ElForm']
    ElFormItem: (typeof import('element-plus/es'))['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: (typeof import('element-plus/es'))['ElImage']
    ElImageViewer: (typeof import('element-plus/es'))['ElImageViewer']
    ElInput: (typeof import('element-plus/es'))['ElInput']
    ElOption: (typeof import('element-plus/es'))['ElOption']
    ElPopconfirm: (typeof import('element-plus/es'))['ElPopconfirm']
    ElPopover: (typeof import('element-plus/es'))['ElPopover']
    ElProgress: (typeof import('element-plus/es'))['ElProgress']
    ElRow: (typeof import('element-plus/es'))['ElRow']
    ElSelect: (typeof import('element-plus/es'))['ElSelect']
    ElSkeleton: (typeof import('element-plus/es'))['ElSkeleton']
    ElSkeletonItem: (typeof import('element-plus/es'))['ElSkeletonItem']
    ElTabPane: (typeof import('element-plus/es'))['ElTabPane']
    ElTabs: (typeof import('element-plus/es'))['ElTabs']
    ElTag: (typeof import('element-plus/es'))['ElTag']
    ElTooltip: (typeof import('element-plus/es'))['ElTooltip']
    ElUpload: (typeof import('element-plus/es'))['ElUpload']
    Emoji: typeof import('./src/components/Emoji/index.vue')['default']
    FriendOrGroupList: typeof import('./src/components/FriendOrGroupList/index.vue')['default']
    HeaderMenu: typeof import('./src/components/HeaderMenu/index.vue')['default']
    Index2: (typeof import('./src/components/MessageDetail/index2.vue'))['default']
    MarkDownEdit: typeof import('./src/components/MarkDownEdit/index.vue')['default']
    MessageDetail: typeof import('./src/components/MessageDetail/index.vue')['default']
    MessageList: typeof import('./src/components/MessageList/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/Search/index.vue')['default']
    SpaceList: typeof import('./src/components/SpaceList/index.vue')['default']
    Toast: typeof import('./src/components/Toast/index.vue')['default']
    TopDrag: typeof import('./src/components/TopDrag/index.vue')['default']
    Windows: (typeof import('./src/components/Windows/index.vue'))['default']
    WindowsBtn: typeof import('./src/components/WindowsBtn/index.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
